
// SW INITIALIZATION
#define ANIMATION_BOOK_JSON_SIZE 2000 // set number equal to length of the JSON string or more

// HW INITIALIZAITON
#define LED_DISPLAY_WIDTH 16
#define LED_DISPLAY_HEIGHT 16
#define LEDS_PER_DISPLAY LED_DISPLAY_WIDTH *LED_DISPLAY_HEIGHT
#define DATA_PIN_LEFT 4
#define DATA_PIN_RIGHT 14
#define BRIGHTNESS 64

// BEHAVIOUR INITIALIZATION
#define STARTUP_ANIMATION "idle"
